// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RecieveMessage_RecieveAndBroadcastMessage_FullMethodName = "/ChitChatty.RecieveMessage/RecieveAndBroadcastMessage"
)

// RecieveMessageClient is the client API for RecieveMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecieveMessageClient interface {
	RecieveAndBroadcastMessage(ctx context.Context, in *ClientSendMessage, opts ...grpc.CallOption) (*ServerBroadcastMessage, error)
}

type recieveMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewRecieveMessageClient(cc grpc.ClientConnInterface) RecieveMessageClient {
	return &recieveMessageClient{cc}
}

func (c *recieveMessageClient) RecieveAndBroadcastMessage(ctx context.Context, in *ClientSendMessage, opts ...grpc.CallOption) (*ServerBroadcastMessage, error) {
	out := new(ServerBroadcastMessage)
	err := c.cc.Invoke(ctx, RecieveMessage_RecieveAndBroadcastMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecieveMessageServer is the server API for RecieveMessage service.
// All implementations must embed UnimplementedRecieveMessageServer
// for forward compatibility
type RecieveMessageServer interface {
	RecieveAndBroadcastMessage(context.Context, *ClientSendMessage) (*ServerBroadcastMessage, error)
	mustEmbedUnimplementedRecieveMessageServer()
}

// UnimplementedRecieveMessageServer must be embedded to have forward compatible implementations.
type UnimplementedRecieveMessageServer struct {
}

func (UnimplementedRecieveMessageServer) RecieveAndBroadcastMessage(context.Context, *ClientSendMessage) (*ServerBroadcastMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveAndBroadcastMessage not implemented")
}
func (UnimplementedRecieveMessageServer) mustEmbedUnimplementedRecieveMessageServer() {}

// UnsafeRecieveMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecieveMessageServer will
// result in compilation errors.
type UnsafeRecieveMessageServer interface {
	mustEmbedUnimplementedRecieveMessageServer()
}

func RegisterRecieveMessageServer(s grpc.ServiceRegistrar, srv RecieveMessageServer) {
	s.RegisterService(&RecieveMessage_ServiceDesc, srv)
}

func _RecieveMessage_RecieveAndBroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecieveMessageServer).RecieveAndBroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecieveMessage_RecieveAndBroadcastMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecieveMessageServer).RecieveAndBroadcastMessage(ctx, req.(*ClientSendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RecieveMessage_ServiceDesc is the grpc.ServiceDesc for RecieveMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecieveMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChitChatty.RecieveMessage",
	HandlerType: (*RecieveMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecieveAndBroadcastMessage",
			Handler:    _RecieveMessage_RecieveAndBroadcastMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
